### ISSUE TITLE
Possible blocking issue

### ISSUE THREAD

**Issue by slifin** [monovaldes/vscode-linter-codeclimate#1]
There's a bit of time here where I am unable to move my cursor, and then all the actions that I did make happen all at once at the end, it's hard to convey but look for the rapid movement all at once at the end of this gif:
![2018-03-15 16 26 09](https://user-images.githubusercontent.com/198857/37476752-edd2b33e-286d-11e8-9b27-682f8647e132.gif)

It feels like what is happening is on lint the thread is being blocked until codeclimate comes back with an answer which prevents me from navigating my code in the mean time

After disabling codeclimate linter in visual studio code and reloading:
![2018-03-15 16 27 32](https://user-images.githubusercontent.com/198857/37476725-d4eb0dbc-286d-11e8-987d-14c0ba35c619.gif)
Movement in this gif was unhindered

**Comment by monovaldes** [comment]
Hi @slifin, sadly, by the time I created the addon, I couldn't get execAsync/spawn to function properly (ref: [code](https://github.com/monovaldes/vscode-linter-codeclimate/blob/master/src/codeclimate.ts#L42)). By then spawning decoupled sub-processes, (in this case `codeclimate analyze`, which invokes a docker exec underneath) never returned the analysis result. I'll look again into it soon, for now, you are welcome to fork and try fixing this up.

Best regards.

**Comment by monovaldes** [comment]
Hi again @slifin, I've managed to call the analyzer via spawn, also made a few performance improvements. Feel free to test again to see if this resolves your issue.
