### ISSUE TITLE
Breaks vim plugin

### ISSUE THREAD

**Issue by suan** [monovaldes/vscode-linter-codeclimate#2]
All vim keys don't work, and strangely even with vim extension uninstalled pressing enter doesn't insert a newline! Possibly related to https://github.com/monovaldes/vscode-linter-codeclimate/issues/1

**Comment by monovaldes** [comment]
hi @suan, i cannot reproduce your issue, CodeClimate analyze by itself requires a load of resources, maybe it ended up blocking your main input for a moment... even so, I've made some improvements in the plugin's performance, feel free to test them out.
